on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main
      - "release/*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Run tests
        run: echo "Running tests..."